[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hatchproject"
dynamic = ["version"]
description = "my first HatchProject created during Jan Kokemuller's Hatch training"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Adrian Carauleanu", email = "adrian.carauleanu@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.scripts]
hatchproject = "hatchproject.cli:main"

[project.urls]
Documentation = "https://github.com/Adrian Carauleanu/hatchproject#readme"
Issues = "https://github.com/Adrian Carauleanu/hatchproject/issues"
Source = "https://github.com/Adrian Carauleanu/hatchproject"

[tool.hatch.version]
path = "src/hatchproject/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/hatchproject"]

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/hatchproject tests}"

[tool.coverage.run]
source_pkgs = ["hatchproject", "tests"]
branch = true
parallel = true
omit = [
  "src/hatchproject/__about__.py",
]

[tool.coverage.paths]
hatchproject = ["src/hatchproject", "*/hatchproject/src/hatchproject"]
tests = ["tests", "*/hatchproject/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
